CREATE TABLE `bo`.`image` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FileType` VARCHAR(45) NOT NULL,
  `FileSize` INT UNSIGNED NOT NULL,
  `Link` VARCHAR(250) NOT NULL,
  `FileID` VARCHAR(250) NOT NULL,
  `uploaddatetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);
